Initial openapi.yml and package.json (no endpoints yet)
NemProject/nem-openapi pull request #1
Opened 2021-09-06 17:46 UTC by fboucquez

Endpoints and schemas would be added one by one, not in this PR. We should create a list of endpoints/issues from https://nemproject.github.io/ and work on them. Schemas should be generated from catbuffer when possibble.

2021-09-06 18:02 UTC, gimre-xymcity approved these changes

2021-09-06 18:02 UTC, gimre-xymcity commented on package.json
> +  "description": "OpenAPI Specification of Nis1 Rest interface",
Nem/NEM REST interface

2021-09-06 20:30 UTC, Jaguar0625 requested changes
have you reviewed these?
https://gist.github.com/kengos/3b0620636fc6775b07f3e4b1288b5c3b

2021-09-06 20:30 UTC, Jaguar0625 commented on spec/openapi.yml
> +      description: 'Huge Alice Mainnet'
you should use NGL (@wayonb) servers

2021-09-07 01:25 UTC, fboucquez commented
> have you reviewed these?
> https://gist.github.com/kengos/3b0620636fc6775b07f3e4b1288b5c3b

I didn't know it. Thanks! What should we do? I think we still need an official nem open API. Splitting the file is also recommended. 

We can use that file as a point of reference while adding the other endpoints. Each endpoint should be tested against a running server though.

2021-09-07 01:55 UTC, fboucquez commented on spec/openapi.yml
> +      description: 'Huge Alice Mainnet'
I thought Huge Alices were the (most) official nodes. Happy to change the URLs.

2021-09-07 14:16 UTC, Jaguar0625 commented on spec/openapi.yml
> +      description: 'Huge Alice Mainnet'
yes, please change. ask @wayonb for nodes.

2021-09-07 14:17 UTC, Jaguar0625 approved these changes

2021-09-08 18:57 UTC, fboucquez commented on spec/openapi.yml
> +      description: 'Huge Alice Mainnet'
I've asked, http://54.170.97.221:7890 is the only NGL mainnet. No domain yet.

2021-09-09 14:06 UTC, merged